#!/usr/bin/env node

// Integration test for verify_balance circuit against Sepolia testnet.
//
// Prerequisites:
//   - PRIVATE_KEY env var set to a funded Sepolia wallet
//   - ALCHEMY_API_KEY env var set (or provide RPC_URL directly)
//   - nargo installed (~/.nargo/bin/nargo)
//
// Usage:
//   node integration.mjs              # Execute only (witness generation + constraint check)
//   node integration.mjs --prove      # Full end-to-end: execute + prove + verify
//
// Or with explicit config:
//   RPC_URL=https://eth-sepolia.g.alchemy.com/v2/KEY \
//   CHAIN_ID=11155111 \
//   PRIVATE_KEY=0x... \
//   PUBLIC_BALANCE=0.001 \
//   node integration.mjs --prove

import { createPublicClient, http, formatEther, hexToBytes } from 'viem';
import { privateKeyToAccount } from 'viem/accounts';
import { secp256k1 } from '@noble/curves/secp256k1';
import { writeFileSync, existsSync } from 'node:fs';
import { spawn, execSync } from 'node:child_process';
import { resolve } from 'node:path';

import {
  CIRCUIT_DIR, ETH_PROOFS_DIR, ORACLE_DIR, YARN_BIN,
  PRIVATE_KEY, CHAIN_ID, RPC_URL,
  PUBLIC_BALANCE_ETH, NULLIFIER_BALANCE_ETH, BLOCK_NUMBER,
  PROVE_MODE, NARGO_BIN, BB_BIN,
} from './constants.mjs';

import {
  ethToWei, toU8Array, formatProverArray,
  log, logError, getChain, runCommand,
} from './utils.mjs';

// ---------------------------------------------------------------------------
// Validate required config
// ---------------------------------------------------------------------------
if (!PRIVATE_KEY) {
  logError('PRIVATE_KEY environment variable is required.');
  console.error('  Set it to a funded Sepolia wallet private key (0x-prefixed).');
  process.exit(1);
}
if (!RPC_URL) {
  logError('RPC_URL or ALCHEMY_API_KEY environment variable is required.');
  console.error('  Sepolia: RPC_URL=https://eth-sepolia.g.alchemy.com/v2/KEY');
  console.error('  Or set ALCHEMY_API_KEY and CHAIN_ID=11155111');
  process.exit(1);
}
if (!existsSync(ETH_PROOFS_DIR)) {
  logError(`eth-proofs not found in nargo cache at ${ETH_PROOFS_DIR}`);
  console.error('  Run "nargo check" first to fetch dependencies.');
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Step 1: Sign the identity message
// ---------------------------------------------------------------------------
async function signIdentityMessage(privateKey) {
  const account = privateKeyToAccount(privateKey);
  log(`Account address: ${account.address}`);

  const message = 'RedactedChat:v0:identity';
  const signature = await account.signMessage({ message });
  log(`Signed identity message`);

  const sigBytes = hexToBytes(signature);
  const r = sigBytes.slice(0, 32);
  const s = sigBytes.slice(32, 64);

  const privKeyBytes = hexToBytes(privateKey);
  const pubKeyPoint = secp256k1.ProjectivePoint.fromPrivateKey(privKeyBytes);
  const pubKeyUncompressed = pubKeyPoint.toRawBytes(false);
  const pubKeyX = pubKeyUncompressed.slice(1, 33);
  const pubKeyY = pubKeyUncompressed.slice(33, 65);

  return {
    address: account.address,
    signature: toU8Array([...r, ...s]),
    publicKeyX: toU8Array(pubKeyX),
    publicKeyY: toU8Array(pubKeyY),
  };
}

// ---------------------------------------------------------------------------
// Step 2: Query chain state
// ---------------------------------------------------------------------------
async function queryChainState(address) {
  const chain = getChain(CHAIN_ID);
  const client = createPublicClient({ chain, transport: http(RPC_URL) });

  let blockNumber;
  if (BLOCK_NUMBER) {
    blockNumber = BLOCK_NUMBER;
  } else {
    blockNumber = await client.getBlockNumber();
    if (blockNumber > 5n) blockNumber = blockNumber - 3n;
  }

  const balance = await client.getBalance({ address, blockNumber });
  log(`Block number: ${blockNumber}`);
  log(`On-chain balance: ${formatEther(balance)} ETH`);

  return { blockNumber, balance };
}

// ---------------------------------------------------------------------------
// Step 3: Generate Prover.toml
// ---------------------------------------------------------------------------
function generateProverToml({ chainId, blockNumber, publicBalance, nullifierBalance, signature, publicKeyX, publicKeyY }) {
  return [
    `# Auto-generated by integration test`,
    `# Chain: ${chainId}, Block: ${blockNumber}`,
    ``,
    `chain_id = ${chainId}`,
    `block_number = ${blockNumber}`,
    `public_balance = "${publicBalance}"`,
    ``,
    `nullifier_balance = "${nullifierBalance}"`,
    `signature = ${formatProverArray(signature)}`,
    `public_key_x = ${formatProverArray(publicKeyX)}`,
    `public_key_y = ${formatProverArray(publicKeyY)}`,
    ``,
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Step 4: Start oracle server
// ---------------------------------------------------------------------------
function startOracleServer() {
  return new Promise((resolvePromise, reject) => {
    const env = { ...process.env };

    if (CHAIN_ID === 1) {
      env.ETHEREUM_JSON_RPC_API_URL = RPC_URL;
    } else if (CHAIN_ID === 11155111) {
      env.ETHEREUM_JSON_RPC_API_URL_SEPOLIA = RPC_URL;
    }

    log(`Starting oracle server (CHAIN_ID=${CHAIN_ID})`);

    const yarnCachePath = resolve(ETH_PROOFS_DIR, '.yarn/cache');
    if (!existsSync(yarnCachePath)) {
      log('Installing oracle server dependencies (first time only)...');
      execSync(`node ${YARN_BIN} install`, { cwd: ETH_PROOFS_DIR, stdio: 'inherit', env });
    }

    const child = spawn('node', [YARN_BIN, 'oracle-server'], {
      cwd: ORACLE_DIR,
      env,
      stdio: ['ignore', 'pipe', 'pipe'],
    });

    let started = false;
    const timeout = setTimeout(() => {
      if (!started) {
        reject(new Error('Oracle server failed to start within 15 seconds'));
        child.kill();
      }
    }, 15000);

    function checkForStartup(data) {
      const text = data.toString();
      if (!started && text.includes('listening')) {
        started = true;
        clearTimeout(timeout);
        log('Oracle server started on http://localhost:5555');
        resolvePromise(child);
      }
    }

    child.stdout.on('data', checkForStartup);
    child.stderr.on('data', checkForStartup);
    child.on('error', (err) => { clearTimeout(timeout); reject(new Error(`Failed to start oracle server: ${err.message}`)); });
    child.on('exit', (code) => { if (!started) { clearTimeout(timeout); reject(new Error(`Oracle server exited with code ${code} before starting`)); } });
  });
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
async function main() {
  console.log('');
  log('=== Verify Balance Integration Test ===');
  log(`Config: CHAIN_ID=${CHAIN_ID}`);
  console.log('');

  // Step 1: Sign
  log('--- Step 1: Signing identity message ---');
  const { address, signature, publicKeyX, publicKeyY } = await signIdentityMessage(PRIVATE_KEY);

  // Step 2: Query chain
  log('--- Step 2: Querying chain state ---');
  const { blockNumber, balance } = await queryChainState(address);

  const publicBalanceWei = ethToWei(PUBLIC_BALANCE_ETH);
  const nullifierBalanceWei = ethToWei(NULLIFIER_BALANCE_ETH);

  if (publicBalanceWei > balance) {
    logError(`PUBLIC_BALANCE (${PUBLIC_BALANCE_ETH} ETH) exceeds on-chain balance (${formatEther(balance)} ETH)`);
    process.exit(1);
  }
  if (nullifierBalanceWei > balance) {
    logError(`NULLIFIER_BALANCE (${NULLIFIER_BALANCE_ETH} ETH) exceeds on-chain balance (${formatEther(balance)} ETH)`);
    process.exit(1);
  }
  log(`Claiming balance: ${PUBLIC_BALANCE_ETH} ETH (${publicBalanceWei} wei)`);

  // Step 3: Generate Prover.toml
  log('--- Step 3: Generating Prover.toml ---');
  const proverToml = generateProverToml({
    chainId: CHAIN_ID,
    blockNumber: blockNumber.toString(),
    publicBalance: publicBalanceWei.toString(),
    nullifierBalance: nullifierBalanceWei.toString(),
    signature,
    publicKeyX,
    publicKeyY,
  });
  const proverPath = resolve(CIRCUIT_DIR, 'Prover.toml');
  writeFileSync(proverPath, proverToml);
  log(`Wrote ${proverPath}`);

  // Step 4: Start oracle server
  log('--- Step 4: Starting oracle server ---');
  let oracleProcess;
  try {
    oracleProcess = await startOracleServer();
  } catch (err) {
    logError(err.message);
    process.exit(1);
  }

  try {
    // Step 5: Execute circuit
    log('--- Step 5: Executing circuit ---');
    await runCommand(NARGO_BIN, ['execute', '--oracle-resolver=http://localhost:5555'], CIRCUIT_DIR);
    log('Circuit executed successfully! All constraints satisfied.');

    if (PROVE_MODE) {
      // Step 6: Generate proof + verification key
      log('--- Step 6: Generating proof (bb prove) ---');
      const targetDir = resolve(CIRCUIT_DIR, 'target');
      const circuitJson = resolve(targetDir, 'verify_balance.json');
      const witnessGz = resolve(targetDir, 'verify_balance.gz');
      await runCommand(BB_BIN, [
        'prove', '-b', circuitJson, '-w', witnessGz, '--write_vk', '-o', targetDir,
      ], CIRCUIT_DIR);
      log('Proof generated successfully!');

      // Step 7: Verify the proof
      log('--- Step 7: Verifying proof (bb verify) ---');
      await runCommand(BB_BIN, [
        'verify',
        '-p', resolve(targetDir, 'proof'),
        '-k', resolve(targetDir, 'vk'),
        '-i', resolve(targetDir, 'public_inputs'),
      ], CIRCUIT_DIR);
      log('Proof verified successfully!');
    }

    console.log('');
    log('=== INTEGRATION TEST PASSED ===');
    log('The circuit correctly verified:');
    log('  - ECDSA signature over identity message');
    log('  - Account balance via Ethereum state proof (oracle + MPT)');
    log('  - Balance >= claimed amount');
    log('  - Deterministic nullifier derivation');
    if (PROVE_MODE) {
      log('  - ZK proof generated and verified (bb prove + bb verify)');
    }
    console.log('');
  } finally {
    log('Stopping oracle server...');
    oracleProcess.kill('SIGTERM');
    await new Promise(r => setTimeout(r, 1000));
  }
}

main().catch((err) => {
  logError(err.message);
  process.exit(1);
});
